import { Common } from "./Home";

export const ourLastestPage: Common[] = [
  {
    srcImg: { imgItem: "/images/product-item/item-collect-1.jpg" },
    label: "BSC",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    ETH: 5.23,
    dollar: 32.42,
    showPrice: false,
    showStyleOurLast: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-2.jpg" },
    label: "BSC",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    ETH: 5.23,
    dollar: 32.42,
    showPrice: false,
    showStyleOurLast: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-3.jpg" },
    label: "BSC",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    ETH: 5.23,
    dollar: 32.42,
    showPrice: false,
    showStyleOurLast: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-4.jpg" },
    label: "BSC",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    ETH: 5.23,
    dollar: 32.42,
    showPrice: false,
    showStyleOurLast: true,
  },
];

export const trendyCollectionsPage: Common[] = [
  {
    srcImg: { imgItem: "/images/product-item/item-collect-1.jpg" },
    label: "RUN",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    showPrice: true,
    showAvt: true,
    showStyleLabel: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-2.jpg" },
    label: "RUN",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    showPrice: true,
    showAvt: true,
    showStyleLabel: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-3.jpg" },
    label: "RUN",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    showPrice: true,
    showAvt: true,
    showStyleLabel: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-4.jpg" },
    label: "RUN",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    showPrice: true,
    showAvt: true,
    showStyleLabel: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-5.jpg" },
    label: "RUN",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    showPrice: true,
    showAvt: true,
    showStyleLabel: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-6.jpg" },
    label: "RUN",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    showPrice: true,
    showAvt: true,
    showStyleLabel: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-7.jpg" },
    label: "RUN",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    showPrice: true,
    showAvt: true,
    showStyleLabel: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-8.jpg" },
    label: "RUN",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    showPrice: true,
    showAvt: true,
    showStyleLabel: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-9.jpg" },
    label: "RUN",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    showPrice: true,
    showAvt: true,
    showStyleLabel: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-10.jpg" },
    label: "RUN",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    showPrice: true,
    showAvt: true,
    showStyleLabel: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-11.jpg" },
    label: "RUN",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    showPrice: true,
    showAvt: true,
    showStyleLabel: true,
  },
  {
    srcImg: { imgItem: "/images/product-item/item-collect-12.jpg" },
    label: "RUN",
    srcAvt: {
      img1: "/images/avatar/avt-8.jpg",
      img2: "/images/avatar/avt-9.jpg",
      img3: "/images/avatar/avt-10.jpg",
      img4: "/images/avatar/avt-11.jpg",
    },
    title: "‘’3D Space Rocket With Smoke Premium’’",
    avatar: "/images/avatar/avt-7.jpg",
    name: "Daniel M. Bivens",
    position: "Creator",
    isDiabledCountdown: false,
    showPrice: true,
    showAvt: true,
    showStyleLabel: true,
  },
];
